buildscript {
    repositories {
        mavenLocal()
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://maven.aliyun.com/repository/google" }
        maven { url "https://repo.huaweicloud.com/repository/maven/" }
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://maven.aliyun.com/repository/google" }
        maven { url "https://repo.huaweicloud.com/repository/maven/" }
    }
}
